### PR TITLE
Move all sources and headers to Makefile.sources

### PR DESCRIPTION
**Pull request by anood**

### CODE REVIEW

**Comment by khaledhosny** [comment]
I still don’t understand what is the purpose of this pull request, your are giving 0 context or rationale.

**Comment by behdad** [comment]
Perhaps to include them from nmake build system.  We recently did that in HarfBuzz.

**Comment by anood** [comment]
As Bahdad said, I changed them to include them from nmake. In future work
we don't need to add any source or header in Makefile, we just add it to
Makefile.sources.

**Comment by khaledhosny** [comment]
OK, you will have to do the actual NMake integration as well, no point in merging this change prematurely otherwise. You can re-use this PR for the future NMake work.

**Pull request closed without merging**
