### PR TITLE
New API

### PR DESCRIPTION
**Pull request by khaledhosny**
The current Raqm API is not very extensible and does not fit the new rule of libraqm as a shared library. This pull request rewrites most of the code to provide a new API that I think is extensible enough to allow us to extend libraqm in the future without breaking the API (and hopefully the ABI, though  this might be a bit harder).

The new API is documented using [gtk-doc](https://developer.gnome.org/gtk-doc-manual/), and Travis CI is setup to push the built HTML documentation to:
http://host-oman.github.io/libraqm

I also reformatted the code because I didn’t like the old code style much, hopefully it isn’t too much different.

### CODE REVIEW

**Comment by khaledhosny** [comment]
@anood @asmaAL-Bahanta @ShamsaHamed @mzn723 @ibtisamN

**Comment by khaledhosny** [comment]
@AliYousuf

**Comment by khaledhosny** [comment]
@AliYousuf

**Comment by dawoodalbadi** [comment]
It seems that it is a nice API 
good work
regards

**Comment by khaledhosny** [comment]
Merged.

**Comment by ShamsaHamed** [comment]
It seem good.
I found it is easy to use and the documentation give enough help.

**Comment by AliYousuf** [comment]
It is good idea.
Now libraqm work with my project.

**Pull request merged**
